### ISSUE TITLE
Null reference exception when trying to execute command after reaching maximum pool of opened connections

### ISSUE THREAD

**Issue by imadhajjchahine** [MonetDB/MonetDB-.Net#1]
Hi,

When the number of opened connections exceeds the poolmaximum settings, instead of throwing an exception when trying to open a new connection and execute a command, the pool.dequeue() returns a null socket and later it throws an object null reference exception.

Thanks.

**Comment by MitchellWeg** [comment]
Hey,
do you have some kind of an example for me to test?

**Comment by imadhajjchahine** [comment]
Hope this will help.

[TestMethod]
public void TestConnectionPoolingExceedMax()
{
    //This test is intended to be run through a debugger and see if the connection pooling is 
    //dynamically creating and destroying the connection pools.
    //Only run this test, because the other tests will mess up the connection pool settings...
    //I know it's not very TDD and this is a code smell, but this is pretty standard fare for
    //database connectivity.
    var modifiedConnString = TestConnectionString + "poolminimum=1;poolmaximum=20;";
    var connections = new MonetDbConnection[21];

    for (var i = 0; i < connections.Length; i++)
    {
        connections[i] = new MonetDbConnection(modifiedConnString);
        connections[i].Open();
        var cmd = new MonetDbCommand("select 1", connections[i]);
        cmd.ExecuteScalar();
    }

    foreach (var connection in connections)
    {
        connection.Close();
    }
}

**Comment by MitchellWeg** [comment]
It now throws an error when the pool maximum is exceeded. However, I get a very different exception: System.ObjectDisposedException. 
Do you get this aswell?

**Comment by imadhajjchahine** [comment]
no after running the test method above, i am getting:
Message: Test method UnitTests.UnitTest.TestConnectionPoolingExceedMax threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by MitchellWeg** [comment]
hmmm, that is weird, I copy and pasted your test and for me it just succeeds. Is this the full code?

**Comment by imadhajjchahine** [comment]
Hi,
After pulling your changes the exception "Max number of connections exceeded" is thrown and the test method "ZTestConnectionPoolingExceedMax" you added is successful. 

I didnt get System.ObjectDisposedException.

**Comment by MitchellWeg** [comment]
Great! I will close this issue now. If this somehow persists, feel free to open it again.
