### ISSUE TITLE
Parameters aren't handled correctly when there are quotes in the SQL query

### ISSUE THREAD

**Issue by Petelids** [MonetDB/MonetDB-.Net#3]
When using parameters in a query, if there are quotes before the parameters, the query will fail due to incorrect SQL being generated.

With the current code this test will pass:

    [TestMethod]
    public void TestParametersWithQuotes()
    {
        using (var connection = new MonetDbConnection(TestConnectionString))
        {
            connection.Open();

            using (var command = connection.CreateCommand())
            {
                command.CommandText = $"SELECT @param1 as m, 'q \"q' as n";

                var param = command.CreateParameter();
                param.ParameterName = "@param1";
                param.Value = 1;
                command.Parameters.Add(param);

                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Assert.AreEqual(1, reader.GetInt32(0));
                        Assert.AreEqual("q \"q", reader.GetString(1));
                    }
                }
            }
        }
    }

as it correctly generates the SQL `SELECT 1 as m, 'q "q' as n`

However, swapping the quoted string with the parameter causes the test to fail:

    [TestMethod]
    public void TestParametersWithQuotes2()
    {
        using (var connection = new MonetDbConnection(TestConnectionString))
        {
            connection.Open();

            using (var command = connection.CreateCommand())
            {
                command.CommandText = $"SELECT 'q \"q' as n, @param1 as m";

                var param = command.CreateParameter();
                param.ParameterName = "@param1";
                param.DbType = DbType.Int32;
                param.Value = 1;
                command.Parameters.Add(param);

                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Assert.AreEqual("q \"q", reader.GetString(0));
                        Assert.AreEqual(1, reader.GetInt32(1));
                    }
                }
            }
        }
    }

This generates the incorrect SQL `SELECT 'q "q' as n, @param1 as m` which leads to an error in Monet of

> !ERROR: ParseException:SQLparser:42000!syntax error, unexpected AT in: "select 'q "q' as n, @"

Note that this scenario isn't as unlikely as it seems due to dates being replaced with quoted strings. This means a query such as

`select x from y where someDate >= @startDate and someDate < @endDate`

ends up being sent to Monet as

`select x from y where someDate >= '1970-01-01 00:00:00' and someDate<@endDate`

which will fail.

I believe the bug is in the handling of quotes in the `ApplyParameter` method in `MonetDbCommand.cs`.

**Comment by MitchellWeg** [comment]
Hi,

Nice find! I've added your example as a unit test, and committed a patch which resolves it. 
Let me know if you have more bugs to fix 👍 .

**Comment by Petelids** [comment]
That's brilliant, thanks @MitchellWeg.
