### ISSUE TITLE
Parameters that are substrings of subsequent parameters cause invalid queries

### ISSUE THREAD

**Issue by Petelids** [MonetDB/MonetDB-.Net#4]
Hi,

It looks like there is an issue in the parameter replacement code where parameters that are substrings of subsequent parameters cause invalid SQL as the substring is replaced in the second parameter. This is perhaps clearer by way of an example:

    [TestMethod]
    public void TestParameters2()
    {
        using (var connection = new MonetDbConnection(TestConnectionString))
        {
            connection.Open();

            using (var command = connection.CreateCommand())
            {
                //note the first param name is a substring of the second param name
                command.CommandText = "select @param1, @param10";

                var param = command.CreateParameter();
                param.ParameterName = "@param1";
                param.Value = "SomeText";
                command.Parameters.Add(param);

                var param2 = command.CreateParameter();
                param2.ParameterName = "@param10";
                param2.Value = 2;
                command.Parameters.Add(param2);

                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Assert.AreEqual("SomeText", reader.GetString(0));
                        Assert.AreEqual(2, reader.GetInt32(1));
                    }
                }
            }
        }
    }

The way the parameter replacement code works, this causes the following SQL query to be sent to Monet:

select 'SomeText', 'SomeText'0

because both instances of "@param1" have been replaced with "'SomeText'".

**Comment by MitchellWeg** [comment]
Pushed a fix for this, and incorporated your unit test. Can you check if it fixes your problem?
