### ISSUE TITLE
GetValue in MonetDbDataReader reads (MonetDB type) decimal and double as (.NET type) float.

### ISSUE THREAD

**Issue by CharlesVDP** [MonetDB/MonetDB-.Net#6]
There's a switch in the GetValue method which returns GetFloat for the cases "double", "double precision", "float", "numeric", "dec", "decimal", and "real".

Looking at the built-in types on the MonetDB site [https://www.monetdb.org/Documentation/SQLLanguage/DataTypes/BuiltinSQLTypes](url) it seems to me that "double", "double precision", and possibly "float" should use the GetDouble method, and that "numeric", "dec", and "decimal" should use the GetDecimal method, and that "real" should be the only type that reads using GetFloat.

The following example fails currently because GetValue will return a System.Single:

        [TestMethod]
        public void TestGetValueWithDecimalDbValue()
		{
            // random table name
            var tableName = Guid.NewGuid().ToString();
            decimal value = 0.01m;

            var createScript = string.Format("CREATE TABLE \"{0}\" (value decimal);", tableName);
            var insertScript = string.Format("INSERT INTO \"{0}\" VALUES({1});", tableName, value);
            var selectScript = string.Format("SELECT * FROM \"{0}\";", tableName);
            var dropScript = string.Format("DROP TABLE \"{0}\";", tableName);

            using (var connection = new MonetDbConnection(TestConnectionString))
            {
                connection.Open();

                using (var command = connection.CreateCommand())
                {
                    // create table
                    command.CommandText = createScript;
                    command.ExecuteNonQuery();

                    // insert into
                    command.CommandText = insertScript;
                    // rows affected 0 or 1
                    command.ExecuteNonQuery();

                    // select from
                    command.CommandText = selectScript;

                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Assert.AreEqual(typeof(decimal), reader.GetValue(0).GetType());
                        }
                    }

                    // drop table
                    command.CommandText = dropScript;
                    command.ExecuteNonQuery();
                }
            }
        }

There also seem to be a few more examples of this issue in the TypeExt class but I haven't looked into them thoroughly.

**Comment by MitchellWeg** [comment]
Thanks for the hard work! I adressed this in the latest commit, and incorporated your unit test.
